-- Seed: West Malaysia courses (par per hole). Generated by scripts/gen-course-migration.mjs from scripts/courses.seed.json.
-- Imported rows are flagged unverified; players can correct them in the app.

with c as (insert into courses (name, state, source, verified) values ('Austin Heights', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,3,4,5,4,4,5,4,5,3,4,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Austin Hills', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,3,4,5,4,4,5,4,5,3,4,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Daiman 18', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,5,3,3,4,4,4,5,3,5,4,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Forest City 3rd Golf Course', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,4,5,3,4,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Forest City Classic Golf Course', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,3,4,5,4,4,3,4,5,4,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Forest City Legacy Golf Course', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,4,5,3,4,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Horizon Hills', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,5,4,3,4,4,4,3,5,4,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Impian Emas Golf & Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,3,5,4,4,4,5,3,4,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Seri Delima', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,3,4,4,4,4,4,5,3,5,3,4,4,4,4,4,5,3]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Tanjong Emas', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[3,4,4,4,3,4,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kluang Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[3,5,3,4,5,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kukup Golf Course', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,4,4,3,5,5,4,4,3,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Nam Heng Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[3,4,3,4,5,4,4,4,5,3,4,3,4,5,4,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Octville Christine Resort', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,3,5,4,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Octville Golf', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,3,5,4,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Orchard Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,4,3,5,4,3,4,5,4,4,3,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Palm Resort', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,5,3,4,4,5,3,4,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Palm Villa', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,5,4,4,3,4,4,4,5,3,4,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Permas Jaya Golf Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[4,3,5,4,3,4,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Ponderosa Golf and Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,4,5,3,4,5,4,5,3,4,4,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Pulai Springs Resort', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[4,4,3,4,3,5,4,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Sebana Cove Resort', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,4,3,5,4,4,5,4,4,3,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Sebana Golf', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,4,3,5,4,4,5,4,4,3,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Segamat Country Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[4,4,4,4,4,4,4,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Senibong (Porresia)', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,3,4,5,3,5,4,4,4,4,5,5,4,4,3]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Star Hill Golf & County Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,3,5,4,3,4,4,4,5,3,4,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Tanjong Puteri', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,4,5,3,4,4,3,4,4,5,3,4,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Tanjung Emas Golf Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[3,4,4,4,3,4,5,4,4,3,4,4,4,3,4,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Els Club', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,3,4,5,5,4,5,3,4,4,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Els Club Desaru Coast (Ocean Course)', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,5,3,4,5,4,5,4,4,3,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Els Club Desaru Coast (Valley Course)', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,5,3,4,5,4,5,4,4,3,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Legends', 'Johor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,3,4,5,4,3,4,4,4,3,5,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Jalil Golf & Country Resort', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,3,4,4,4,3,5,4,5,4,4,3,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Perkhidmatan Awam', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,3,4,4,5,3,4,4,5,4,3,4,5,3,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Titiwangsa', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[3,4,5,3,4,5,4,4,4,3,4,5,3,4,5,4,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('KGPA - Kelab Golf Perkhidmatan Awam', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,3,4,5,3,3,5,4,4,5,3,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('KLGCC Kuala Lumpur Golf & Country Club', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,3,4,4,4,4,4,4,5,4,4,3,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Royal Selangor Golf Club', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,3,4,5,3,4,4,4,4,3,5,4,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Tropicana', 'Kuala Lumpur', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,4,5,4,3,4,4,4,3,5,4,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Dickson Bay', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,5,4,3,4,5,4,4,3,4,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Era Golf & Country Resort', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,5,3,5,4,4,4,4,3,4,5,4,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Gemas Golf Resort', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,3,4,4,5,3,4,4,4,5,3,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kota Seriemas Golf & Country Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,4,4,3,5,3,4,5,4,4,4,3,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Nilai Springs Golf & Country Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,3,4,4,3,5,4,4,5,4,4,3,4,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Port Dickson Golf and Country Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,4,3,5,4,5,5,4,5,3,4,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Royal Palm Springs Golf Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,5,4,3,4,5,4,4,3,4,3,4,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Royal Seri Menanti Golf & Country Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,3,4,4,4,5,4,3,5,3,4,4,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Seremban International Golf Club', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,5,4,4,3,4,5,3,4,4,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Staffield', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,3,4,4,4,5,4,3,4,4,4,5,3,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Staffield Country Resort', 'Negeri Sembilan', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,4,5,3,4,3,4,5,3,4,4,4,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Awana Genting Golf Club', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,5,3,4,5,3,4,4,5,5,4,3,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bentong Golf Club', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,4,3,5,4,5,3,4,4,4,5,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Berjaya Hills GCC', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,4,3,4,5,4,5,3,4,4,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Cameron Highlands Golf Club', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,4,5,3,4,5,3,4,3,4,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Bentong', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,4,3,5,4,5,3,4,4,4,5,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Bentung', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,4,3,5,4,5,3,4,4,4,5,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Diraja Pekan', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,4,3,5,3,4,4,4,3,4,5,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Sultan Ahmad Shah', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,4,5,3,4,4,4,3,5,4,3,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Lanjut Beach & Golf Resort', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,4,3,5,3,5,4,4,5,3,4,4,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Mahkota Golf & Country Club', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,5,4,4,3,5,4,3,5,4,4,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Royal Pahang Golf Club', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,3,5,4,4,3,4,4,3,5,3,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Selesa Golf Course', 'Pahang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,3,4,4,5,4,3,5,3,4,5,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Jambul', 'Penang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,5,4,3,4,4,4,4,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Jawi Golf Resort', 'Penang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,4,5,4,3,5,5,4,3,4,3,5,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Mountain View Resort', 'Penang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,3,4,5,4,5,4,3,4,4,3,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Penang Golf Club', 'Penang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,5,4,3,4,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Penang Golf Resort', 'Penang', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,4,3,4,3,4,5,5,4,3,4,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Amverton Cove Golf & Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,4,3,4,3,5,4,5,4,3,4,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bangi Golf Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,3,4,4,5,4,4,3,5,4,4,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Berungtung', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,3,4,3,4,5,4,4,4,4,4,5,5,3,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Beruntung Golf and Country Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,3,4,3,4,5,4,4,4,4,4,5,5,3,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Kemuning', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,3,4,4,5,4,4,5,3,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Unggul Golf Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,3,4,4,5,4,4,4,3,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Bukit Utama Golf Course', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[4,5,3,4,4,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Carey Island Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[3,4,4,4,5,3,4,5,4,3,4,4,4,5,3,4,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Danau Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,4,3,4,4,5,4,4,5,3,4,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Danau Golf UKM', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,4,3,4,4,5,4,4,5,3,4,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Glenmarie Golf & Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,3,5,4,4,4,4,5,3,4,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Harvard Jerai & Guthrie', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,3,4,4,4,4,5,4,3,4,5,3,4,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Impian Golf and Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,5,4,3,4,4,4,4,3,4,5,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('IOI Palm Garden Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,5,5,4,3,4,4,5,4,3,5,3,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kajang Hill GC', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,5,3,4,4,4,4,3,4,5,3,4,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Darul Ehsan', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,3,5,5,4,3,5,4,3,4,3,5,5,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf & Country Kuala Kubu Bharu', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,4,5,4,3,3,5,4,3,4,4,3,4,4,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Di Raja Kampung Kuantan', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9], array[4,3,5,3,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Negara Subang', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,4,3,4,3,5,4,4,3,5,3,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Seri Selangor', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,4,5,5,4,3,4,4,4,3,5,3,4,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Sri Morib', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,3,4,5,5,4,4,4,3,4,3,4,5,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Golf Sultan Abdul Aziz Shah', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,5,3,4,4,5,4,5,3,4,4,3,5,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kelab Rekreasi Tentera Udara KRTU', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,5,4,3,5,3,4,4,5,3,4,4,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kinrara', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,3,4,5,4,4,5,4,3,4,5,4,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kota Permai Golf & Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,3,4,3,5,4,4,4,4,5,4,3,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Kundang Lakes Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,5,4,4,5,3,4,5,3,4,5,4,3,4,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Monterez GCC', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,5,3,4,4,4,4,5,4,3,5,4,3,4,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Palm Garden Golf club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,5,5,4,3,4,4,5,4,3,5,3,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Perangsang Templer Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,4,4,4,5,4,3,5,4,5,4,3,4,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Port Klang Golf Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,3,5,3,4,4,4,4,4,4,5,3,5,4,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Rahman Putra', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,3,4,4,4,5,5,4,3,4,4,3,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Saujana Golf & Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,4,4,3,5,4,4,5,4,3,4,5,3,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Serendah Golf Resort', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,5,3,4,5,3,4,4,5,3,5,3,4,4,3,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Seri Selangor Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,3,4,5,5,4,3,4,4,4,3,5,3,4,4,4,5]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('SSG Lembah Beringin', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,3,4,4,5,3,4,4,5,4,4,3,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Subang National Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,4,4,3,5,4,4,3,4,4,3,5,3,4,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Sungai Long GCC', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,3,4,5,4,4,3,4,4,4,5,4,3,5,4,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Tasik Puteri', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,5,4,3,4,3,4,4,5,4,4,4,5,3,4,5,3,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('Templer Park Country Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,3,4,4,4,4,5,3,4,4,3,5,4,4,5,3,4,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('The Mines Resort & Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[4,3,5,4,4,4,3,4,4,4,5,4,4,3,4,3,5,4]) as h(n, p);

with c as (insert into courses (name, state, source, verified) values ('UniPutra Golf Club', 'Selangor', 'golfingrecord.com', false) on conflict (name) do nothing returning id)
insert into course_holes (course_id, hole_no, par) select c.id, h.n, h.p from c, unnest(array[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], array[5,4,4,4,5,3,4,3,4,4,3,4,4,4,4,5,3,5]) as h(n, p);

